const CSS_FUNCTIONS = [
  'rgb',
  'rgba',
  'hsl',
  'hsla',
  'calc',
  'var',
  'linear-gradient',
  'radial-gradient',
  'repeating-linear-gradient',
  'repeating-radial-gradient',
  'conic-gradient',
  'url',
  'attr',
  'cubic-bezier',
  'steps',
  'matrix',
  'translate',
  'translateX',
  'translateY',
  'translateZ',
  'translate3d',
  'scale',
  'scaleX',
  'scaleY',
  'scaleZ',
  'scale3d',
  'rotate',
  'rotateX',
  'rotateY',
  'rotateZ',
  'rotate3d',
  'skew',
  'skewX',
  'skewY',
  'perspective'
];

export type CssFunction = typeof CSS_FUNCTIONS[number];
export const CSS_FUNCTIONS_SET = new Set(CSS_FUNCTIONS);
