const PROPERTIES_REQUIRING_UNITS = [
  'width',
  'height',
  'margin',
  'padding',
  'border',
  'border-width',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',
  'top',
  'right',
  'bottom',
  'left',
  'font-size',
  'min-width',
  'max-width',
  'min-height',
  'max-height',
  'outline-width',
  'letter-spacing',
  'word-spacing',
  'text-indent',
  'perspective',
  'translate',
  'rotate',
  'scale',
  'gap',
  'row-gap',
  'column-gap'
];

export type PropertyRequiringUnit = typeof PROPERTIES_REQUIRING_UNITS[number];
export const PROPERTIES_REQUIRING_SET = new Set(PROPERTIES_REQUIRING_UNITS);
